fix pre push script

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,8 +1,8 @@
 exit_code=0
 
-pnpm -r --no-bail lint || { echo "Lint failed: exit code $?" && exit_code=1; }
+pnpm lint || { echo "Lint failed: exit code $?" && exit_code=1; }
 echo "\n==========================================================================================================\n"
-pnpm -r --no-bail format || { echo "Format failed: exit code $?" && exit_code=1; }
+pnpm format || { echo "Format failed: exit code $?" && exit_code=1; }
 echo "\n==========================================================================================================\n"
 pnpm -r --no-bail ts:check || { echo "TypeScript check failed: exit code $?" && exit_code=1; }
 echo "\n==========================================================================================================\n"
